### ISSUE TITLE
Not an issue: just a thank you note

### ISSUE THREAD

**Issue by FrailWords** [blyssprivacy/sdk#21]
Hi folks, Just wanted send a thank you for implementing this sdk. I am trying to build a simple PIR demo for a class project and your implementation helped me a lot in terms of making it demo'able in a practical scenario like a web app.  This is where my demo exists - https://github.com/FrailWords/blyss-pir.  I still do not understand the PIR details very well from a mathematical point of view but definitely more interested in how it can be abstracted for more practical use and thats why I loved what you've done.

Thank you again,

Regards,

**Comment by neilmovva** [comment]
Thank you for the kind words, we're glad Blyss was useful!
Looking at your project, it looks like you're using Blyss to serve ads privately.
That's a great application for PIR!
