### ISSUE TITLE
Using client on local blyss instance

### ISSUE THREAD

**Issue by ookami125** [blyssprivacy/sdk#26]
Hey I seem to be having an issue with creating a bucket with the endpoint being my local instance. It complains about the endpoint "http://localhost:8008/create" not existing/responding when attempting to create a new bucket with client.create(...). I followed the example in the Readme for starting a local instance, is there something else I need to do? Or are clients not supported on local instances?

**Comment by Katherine-101** [comment]
I have the same issue. Did you solve it?

**Comment by ookami125** [comment]
> I have the same issue. Did you solve it?

No sorry, I stopped trying for now since I was only starting a new project and the early road block just made me drop it. Knowing someone else is having the same problem though I might look into it again soon.

**Comment by menonsamir** [comment]
Apologies for the delay on this!

When I do this from a fresh clone, the local server seems to work:
```sh
$ git clone https://github.com/blyssprivacy/sdk.git
$ cd lib/server
$ cargo run --release

# in another terminal
$ cd examples/node-local
$ npm install
$ npx ts-node main.ts
```

It's not possible to create buckets using the local server - instead, each instance of the local server acts as a single bucket. Are you maybe running the `node` example, instead of the `node-local` example? We can clarify the docs on exactly how the local server differs from the general service.

**Comment by ookami125** [comment]
> It's not possible to create buckets using the local server - instead, each instance of the local server acts as a single bucket. Are you maybe running the `node` example, instead of the `node-local` example? We can clarify the docs on exactly how the local server differs from the general service.

This is the info I wanted to know. It seems the issue I was originally facing is now gone or how I was originally running the example was wrong. I was running node-local, but when I restarted the client the contents of the bucket were lost. This made it look like the only client that could read the info on the server was the client that put it there, which would have been fairly useless. I'm glad that's not the case as this might actually be usable for my purposes. I would probably note exactly what you did here though "each instance of the local server acts as a single bucket." I don't know what misconception I initially had, but I feel like that might have cleared it up.

I'm going to close this issue as it seems that this isn't a problem, but just to ask and avoid another ticket, is there any way to save the contents of the local server? Shutting down the server seems to make it lose all of it's contents.
